-- Seed: 24 posts from the original POSTS array in /design/home.js
-- All published with placeholder content bodies.

INSERT INTO posts (title, slug, content, excerpt, pull_quote, category, read_time, cover_art, text_only, featured, published, published_at) VALUES

('The case for quiet software',
 'quiet-software',
 E'It was a Tuesday morning, and my phone had been quiet for two hours.\n\nThat, more than the coffee, is what I remember about the morning — the slightly embarrassed feeling that I had been working without anyone needing me.\n\n## The case\n\nI want to make the case for **quiet software** — not as an aesthetic, but as a kind of engineering practice.\n\n## Four quiet tools\n\nI keep a small list of tools that have stayed quiet for me over years.\n\n## What''s lost\n\nQuiet software costs something. There is no growth team in here.\n\n## Closing notes\n\nThe reason I am writing this in 2026 and not 2016 is that *loud* software has gotten so good at being loud that the contrast is now obvious.',
 'Notifications are the rain, the interface is the umbrella. A short argument for tools that whisper.',
 NULL,
 'essay', '12 min',
 '{"p1":"#1f2a3a","p2":"#4f6b85","kind":"orb","thumb":"tall"}',
 false, true, true, '2026-04-04 09:00:00+00'),

('Why I still bookmark',
 'why-i-bookmark',
 E'Bookmarks are slow social media for one.\n\nNotes from twelve years of keeping a personal corner of the web.\n\n## The archive\n\nI have been bookmarking things since 2012. That is a long time to keep a habit that no one would notice if I stopped.\n\n## What bookmarks are\n\nA bookmark is a claim about future attention. It says: I believe I will want this again.\n\n## The failure mode\n\nThe failure mode of bookmarking is the same as the failure mode of any collecting practice: you start filing things you will never revisit.',
 'Bookmarks are slow social media for one. Notes from twelve years of keeping a personal corner of the web.',
 NULL,
 'essay', '7 min',
 '{"p1":"#a59883","p2":"#4a3f30","kind":"pages","thumb":"short"}',
 false, false, true, '2026-03-28 09:00:00+00'),

('Editor feels: friction is a feature',
 'editor-feels',
 E'The best writing tools are the ones that resist a little.\n\nOn Markdown, magnets, and intentional drag.\n\n## Resistance as design\n\nFriction in a writing tool is not a bug. It is the editor''s way of saying: slow down, think this through.\n\n## The markdown argument\n\nMarkdown is friction. You have to type asterisks. You have to type backticks. These small obstacles are features.\n\n## Magnets\n\nSome tools attract you to the work. Others repel you from it. The best ones do a little of both.',
 'The best writing tools are the ones that resist a little. On Markdown, magnets, and intentional drag.',
 NULL,
 'craft', '9 min',
 '{"p1":"#c08a64","p2":"#5c3b25","kind":"lines","thumb":"square"}',
 false, false, true, '2026-03-21 09:00:00+00'),

('On letting drafts age',
 'aging-drafts',
 E'A draft is a kind of weather report.\n\nIf you wait, the weather changes — but the place it describes stays the same.\n\n## The patience argument\n\nEvery draft I have published too quickly, I have regretted. Every draft I sat on for a month, I published better.\n\n## What aging does\n\nTime does something to a draft that editing cannot. It makes you forget why you wrote it. That is useful.',
 NULL,
 'A draft is a kind of weather report. If you wait, the weather changes — but the place it describes stays the same.',
 'essay', '4 min',
 NULL,
 true, false, true, '2026-03-14 09:00:00+00'),

('The weather of attention',
 'attention-weather',
 E'Some mornings the mind is overcast. Some afternoons it''s bright and stupid.\n\nA field guide to your own focus.\n\n## The morning\n\nI have kept a log of what I am capable of at different hours. The pattern is embarrassingly consistent.\n\n## Overcast days\n\nOn overcast days I do administrative work. I answer emails. I do not write.\n\n## The field guide\n\nKnowing your own attention weather is not the same as being able to change it. It is the same as knowing whether to bring an umbrella.',
 'Some mornings the mind is overcast. Some afternoons it''s bright and stupid. A field guide to your own focus.',
 NULL,
 'field', '11 min',
 '{"p1":"#b3c4d6","p2":"#4a6178","kind":"wave","thumb":"tall"}',
 false, false, true, '2026-03-07 09:00:00+00'),

('Glassy UIs and the long history of seeing through',
 'glassy-uis',
 E'From medieval reliquaries to liquid glass.\n\nTranslucency is older and weirder than your icon set.\n\n## The reliquary\n\nThe medieval reliquary is a box for holding the bones of saints. It is made of glass so you can see inside without opening it.\n\n## A long history\n\nTranslucency in design has always been about access without contact. The glass lets you see but not touch.\n\n## Liquid glass today\n\nThe frosted glass UI of 2024 is doing something very old: it lets you see the layer beneath without being in it.',
 'From medieval reliquaries to liquid glass. Translucency is older and weirder than your icon set.',
 NULL,
 'craft', '14 min',
 '{"p1":"#dce6ec","p2":"#7d96aa","kind":"glass","thumb":"short"}',
 false, false, true, '2026-02-28 09:00:00+00'),

('What I read in February',
 'reading-stack',
 E'A perfectly ordinary stack of books, with one strange entry that''s been rearranging my month.\n\n## The stack\n\nFive books. Three finished. Two abandoned at the 60% mark, which is my failure mode.\n\n## The strange one\n\nThe strange entry is a 1974 translation of a Swedish novel I found at a stall. I do not know what it is about yet. I am enjoying not knowing.\n\n## On abandoning books\n\nI used to finish every book I started. I am less strict about this now and my reading has improved.',
 'A perfectly ordinary stack of books, with one strange entry that''s been rearranging my month.',
 NULL,
 'reading', '6 min',
 '{"p1":"#a07ab5","p2":"#3d2845","kind":"spines","thumb":"square"}',
 false, false, true, '2026-02-25 09:00:00+00'),

('Systems are sentences',
 'systems-thinking',
 E'How thinking about software like prose changes which parts you care about.\n\n## The sentence model\n\nA sentence has a subject, a verb, and an object. A system has an input, a process, and an output. These are the same shape.\n\n## What changes\n\nWhen you think of a system as a sentence, you start asking: who is the subject? What does the verb actually do? Where does the sentence end?\n\n## The paragraph\n\nA system of systems is a paragraph. The question is whether it has a topic sentence.',
 'How thinking about software like prose changes which parts you care about.',
 NULL,
 'systems', '10 min',
 '{"p1":"#3f7a8c","p2":"#0f2630","kind":"grid","thumb":"tall"}',
 false, false, true, '2026-02-18 09:00:00+00'),

('Walks I take when I''m stuck',
 'walks',
 E'Geography of the small block.\n\nOn the four-block loop that has survived three apartments.\n\n## The loop\n\nI have lived in three apartments in this city. Each one is within walking distance of the others. The loop I walk when stuck is the same loop, adjusted.\n\n## What walking does\n\nWalking is not thinking. It is a kind of not-thinking that sometimes produces thoughts.\n\n## The geography\n\nThe block has a bakery that is always out of the thing I want. This is fine.',
 'Geography of the small block. On the four-block loop that has survived three apartments.',
 NULL,
 'field', '5 min',
 '{"p1":"#6ba39a","p2":"#21443e","kind":"topo","thumb":"wide"}',
 false, false, true, '2026-02-11 09:00:00+00'),

('A taxonomy of restlessness',
 'taxonomy-restless',
 E'There is a restlessness that points at the work.\n\nThere is another that points away. The trick is learning to tell them apart.\n\n## Type one\n\nThe first kind of restlessness is productive. It says: this is not good enough yet. It keeps you at the desk.\n\n## Type two\n\nThe second kind is avoidance dressed in ambition clothes. It says: you should be doing something more important than this. It takes you away from the desk.\n\n## The diagnosis\n\nThe difference, in my experience, is what the restlessness is pointing at.',
 NULL,
 'There is a restlessness that points at the work. There is another that points away. The trick is learning to tell them apart.',
 'essay', '8 min',
 NULL,
 true, false, true, '2026-02-04 09:00:00+00'),

('Tiny tools and the maintenance of joy',
 'tiny-tools',
 E'I rewrote my note-taker for the third time this year.\n\nNotes from someone who knows it''s a defense mechanism.\n\n## The rewrite\n\nI know, and have always known, that the third rewrite of my note-taker is not about the notes. It is about the pleasure of building something small.\n\n## The maintenance of joy\n\nThere is a category of activity that I call maintenance-of-joy work. It does not produce anything. It does not move any needle. But it keeps the machine running.\n\n## The defense mechanism\n\nThe defense mechanism interpretation is also true. Both things are true.',
 'I rewrote my note-taker for the third time this year. Notes from someone who knows it''s a defense mechanism.',
 NULL,
 'craft', '9 min',
 '{"p1":"#c4b294","p2":"#5a4a30","kind":"tools","thumb":"short"}',
 false, false, true, '2026-01-28 09:00:00+00'),

('What the room knows',
 'what-the-room-knows',
 E'On environments that remember things for you, and the strange dignity of a desk left alone.\n\n## The desk\n\nMy desk is a record of unfinished things. The coffee cup marks the morning. The open notebook marks the afternoon. Together they make a kind of calendar.\n\n## What environments know\n\nA room that you work in regularly knows you in a way that a room you visit does not. It has your fingerprints on it, in the literal sense.\n\n## The dignity of leaving things\n\nI have started leaving things out when I stop working. The unfinished sentence. The half-filled page. They are a kind of contract with the morning.',
 'On environments that remember things for you, and the strange dignity of a desk left alone.',
 NULL,
 'field', '7 min',
 '{"p1":"#8a9aab","p2":"#2c3a4c","kind":"room","thumb":"tall"}',
 false, false, true, '2026-01-21 09:00:00+00'),

('What I read in January',
 'reading-jan',
 E'Three novels, one re-read, and an essay that made me retire a sentence I''d been saying for ten years.\n\n## The novels\n\nAll three were recommended to me by different people at the same dinner party. I do not know what to do with this information.\n\n## The re-read\n\nThe re-read was a novel I first read in my early twenties. It is a different book now. I am a different reader.\n\n## The essay\n\nThe essay that retired my sentence was a 2018 piece in a small journal. I had been saying the sentence in lectures. I will not say it again.',
 'Three novels, one re-read, and an essay that made me retire a sentence I''d been saying for ten years.',
 NULL,
 'reading', '6 min',
 '{"p1":"#b594a0","p2":"#3e2a31","kind":"spines","thumb":"square"}',
 false, false, true, '2026-01-14 09:00:00+00'),

('In praise of small pages',
 'small-pages',
 E'Personal sites are vegetable gardens.\n\nThey aren''t trying to feed the world.\n\n## The garden\n\nA vegetable garden in a backyard is not competing with a farm. It is doing something different: growing food for the person who tends it, and maybe their neighbors.\n\n## The small page\n\nA personal website is the same. It is not trying to reach everyone. It is trying to reach the people who are looking for exactly this thing.\n\n## The scale argument\n\nI think the small page is the right scale for writing that is trying to think, rather than writing that is trying to reach.',
 'Personal sites are vegetable gardens. They aren''t trying to feed the world.',
 NULL,
 'essay', '8 min',
 '{"p1":"#7d9b75","p2":"#28402a","kind":"leaves","thumb":"wide"}',
 false, false, true, '2026-01-07 09:00:00+00'),

('Software that doesn''t track me',
 'tracking-less',
 E'A short list of tools I trust, why I trust them, and the failure modes I''ve watched up close.\n\n## The list\n\nI keep a list of software I trust. It is short. I update it slowly.\n\n## What trust means here\n\nTrust, in this context, means: I believe the software is not trying to extract something from me beyond what I have agreed to.\n\n## The failure modes\n\nI have watched several tools I trusted fail in predictable ways. The pattern is consistent: a new revenue requirement, a new metric, a gradual erosion.',
 'A short list of tools I trust, why I trust them, and the failure modes I''ve watched up close.',
 NULL,
 'systems', '13 min',
 '{"p1":"#3a4b66","p2":"#0e1726","kind":"mesh","thumb":"short"}',
 false, false, true, '2025-12-30 09:00:00+00'),

('On rereading',
 'reread',
 E'Rereading is the only honest book review.\n\nThe second time, the book stops trying to charm you — and that''s when it starts telling the truth.\n\n## The first read\n\nThe first time you read a book, you are being seduced. The book is trying to win you over. You are too busy deciding whether to like it to actually read it.\n\n## The second read\n\nThe second time, you know the plot. The seduction is over. Now you can pay attention.\n\n## What the book tells you\n\nThe second reading reveals what the book is actually about, as opposed to what it claims to be about.',
 NULL,
 'Rereading is the only honest book review. The second time, the book stops trying to charm you — and that''s when it starts telling the truth.',
 'reading', '5 min',
 NULL,
 true, false, true, '2025-12-23 09:00:00+00'),

('Keeping a commonplace book in 2026',
 'commonplace',
 E'Why a paper notebook still wins the war for ideas, and how mine has changed shape.\n\n## The commonplace tradition\n\nCommonplace books are as old as literacy. The idea is simple: you copy things out, by hand, into a single book.\n\n## Why paper\n\nI have tried digital commonplacing. It is not the same. The act of copying by hand is not just transcription; it is a kind of slow reading.\n\n## How mine has changed\n\nMy commonplace book used to be organized by topic. Now it is organized by date. I review it quarterly and sort the themes afterward.',
 'Why a paper notebook still wins the war for ideas, and how mine has changed shape.',
 NULL,
 'craft', '11 min',
 '{"p1":"#c9b58a","p2":"#5a4625","kind":"pages","thumb":"tall"}',
 false, false, true, '2025-12-16 09:00:00+00'),

('Five writing rules I broke this year',
 'rules-i-broke',
 E'Adverbs. Em-dashes. Long sentences. Long paragraphs. Caring what people thought.\n\n## Adverbs\n\nI used to avoid adverbs. This year I used one on purpose and it was exactly right.\n\n## Em-dashes\n\nI have always used too many em-dashes. This year I decided to embrace this as a stylistic signature rather than a failure.\n\n## Long sentences\n\nA long sentence, handled well, can carry more than a short one. I gave myself permission to write longer.\n\n## Caring what people thought\n\nThis was the hardest rule to break. I am still working on it.',
 'Adverbs. Em-dashes. Long sentences. Long paragraphs. Caring what people thought.',
 NULL,
 'essay', '7 min',
 '{"p1":"#a07882","p2":"#3a2530","kind":"lines","thumb":"wide"}',
 false, false, true, '2025-12-09 09:00:00+00'),

('Desk archaeology',
 'desk-archeology',
 E'A tour of the things on my desk and what each one is doing, ranked by what they secretly are.\n\n## The coffee cup\n\nOfficially: a coffee cup. Secretly: a timer. When the coffee is cold, it is time to take a break.\n\n## The notebook\n\nOfficially: a notebook. Secretly: a commitment device. Having it out means I am working.\n\n## The headphones\n\nOfficially: headphones. Secretly: a do not disturb sign. They are often not playing anything.\n\n## The lamp\n\nOfficially: a lamp. Secretly: a ritual object. Turning it on is how I start work.',
 'A tour of the things on my desk and what each one is doing, ranked by what they secretly are.',
 NULL,
 'field', '6 min',
 '{"p1":"#9b8f75","p2":"#3a3225","kind":"objects","thumb":"short"}',
 false, false, true, '2025-12-02 09:00:00+00'),

('Long now, short week',
 'long-now',
 E'Planning for the decade is easy. Planning for Thursday is a discipline.\n\n## The long now\n\nI am good at decade-scale thinking. I have clear ideas about where I want to be in ten years, and roughly how to get there.\n\n## Thursday\n\nThursday is harder. Thursday requires me to account for the energy I will actually have, the tasks that are actually urgent, and the work I have been avoiding.\n\n## The discipline\n\nThe discipline is accepting that Thursday-planning is not less important than decade-planning. It is more important, because Thursday is actually going to happen.',
 'Planning for the decade is easy. Planning for Thursday is a discipline.',
 NULL,
 'systems', '9 min',
 '{"p1":"#557a8c","p2":"#1a2c36","kind":"grid","thumb":"square"}',
 false, false, true, '2025-11-25 09:00:00+00'),

('The first paragraph problem',
 'first-paragraph',
 E'Every first paragraph is a door. Most of them open onto the wrong room.\n\n## The wrong room\n\nThe wrong room is the room where you explain what you are about to say. Most first paragraphs are in this room.\n\n## The right room\n\nThe right room is the room where something is already happening. The reader walks in and something is already in motion.\n\n## The solution\n\nThe solution is usually to delete the first paragraph and start with the second.',
 NULL,
 'Every first paragraph is a door. Most of them open onto the wrong room.',
 'essay', '4 min',
 NULL,
 true, false, true, '2025-11-18 09:00:00+00'),

('What I read in November',
 'reading-nov',
 E'Heavier than usual. Two history books, a poetry collection, and a novel I''m still arguing with.\n\n## The history books\n\nBoth were about the same period from different angles. Reading them back to back was disorienting in the best way.\n\n## The poetry collection\n\nI do not usually read poetry. A friend sent this one and I have read it three times.\n\n## The novel\n\nThe novel I am still arguing with is one I would not recommend to most people and cannot stop thinking about.',
 'Heavier than usual. Two history books, a poetry collection, and a novel I''m still arguing with.',
 NULL,
 'reading', '7 min',
 '{"p1":"#8a6f9b","p2":"#2e2138","kind":"spines","thumb":"short"}',
 false, false, true, '2025-11-11 09:00:00+00'),

('The edges of things',
 'edges',
 E'Borders, deadlines, page margins. A little essay about how shapes contain what they contain.\n\n## The margin\n\nA page margin is an agreement. It says: the writing lives here. Everything else is space for the reader.\n\n## The deadline\n\nA deadline is a border in time. It contains the work by setting an edge beyond which nothing can be added.\n\n## What edges do\n\nEdges are not constraints. They are definitions. A thing without edges is not a thing; it is a cloud.',
 'Borders, deadlines, page margins. A little essay about how shapes contain what they contain.',
 NULL,
 'essay', '8 min',
 '{"p1":"#b0bdc7","p2":"#4a5560","kind":"wave","thumb":"tall"}',
 false, false, true, '2025-11-04 09:00:00+00'),

('Workshop notes: building in the open',
 'workshop-notes',
 E'After two months of building in public. What changed in the work, and what changed in me.\n\n## What changed in the work\n\nThe work got more careful. When people are watching, you notice more. You explain your choices before you are asked.\n\n## What changed in me\n\nI became more comfortable with incompleteness. Showing unfinished work is a discipline.\n\n## The unexpected thing\n\nThe unexpected thing was that building in public made the work more mine, not less. Showing it to people clarified what I actually cared about.',
 'After two months of building in public. What changed in the work, and what changed in me.',
 NULL,
 'craft', '12 min',
 '{"p1":"#d39a64","p2":"#5c3a20","kind":"tools","thumb":"wide"}',
 false, false, true, '2025-10-28 09:00:00+00');
